name: "Helm Chart Testing"
description: "Run the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  image:
    description: "The kubeval-helm-chart Docker image to use"
  config:
    description: "The relative path to the ckubeval-helm-chart config file"
  command:
    description: "The kubeval-helm-chart command to run"
    required: true
  kubeconfig:
    description: "The path to the kube config file"
outputs:
  changed:
    description: "Whether or not charts have changed (true/false)"
runs:
  using: "node12"
  main: "main.js"
